tbphp/gpt-load

- README.md
- README_EN.md
- internal/proxy/server.go
- internal/types/types.go
Closes #9 
调整响应超时默认值为600s，并且返回错误状态码。
> Fix timeout too long

- internal/handler/group_handler.go
- web/src/components/keys/GroupFormModal.vue
Closes #16 
- 修改分组名称规则：允许使用小写字母、数字和下划线，长度在 3 到 30 个字符之间
> feat: 分组名称支持更多格式

- internal/app/app.go
- internal/db/migrations/migration.go
- internal/db/migrations/v1.0.13_fix_request_logs.go
- internal/handler/log_handler.go
- internal/models/types.go
- internal/proxy/server.go
- internal/services/request_log_service.go
- internal/types/types.go
- web/src/components/logs/LogTable.vue
Closes #7 
- 调整日志表结构并修复数据
- 日志表冗余group和key字段，不再关联查询
- 优化日志表格展示
> Fix log apikey error

- web/src/components/keys/GroupInfoCard.vue
- web/src/components/keys/KeyTable.vue
- web/src/utils/clipboard.ts
> fix: 修复前端复制兼容性问题

- README.md
- README_EN.md
> docs: 更新docker快速启动方式

- web/src/components/LineChart.vue
- web/src/components/keys/GroupInfoCard.vue
- web/src/components/logs/LogTable.vue
> feat: 前端优化

- internal/container/container.go
- internal/handler/handler.go
- internal/handler/key_handler.go
- internal/handler/log_handler.go
- internal/middleware/middleware.go
- internal/router/router.go
- internal/services/key_service.go
- internal/services/log_service.go
- web/src/api/keys.ts
- web/src/api/logs.ts
- web/src/components/keys/KeyTable.vue
- web/src/components/logs/LogTable.vue
- 分组秘钥增加 导出全部密钥，导出有效密钥，导出无效密钥
- 请求日志增加 导出密钥功能，针对筛选进行导出密钥并去重
> feat: 密钥导出功能

- internal/handler/dashboard_handler.go
- web/src/components/LineChart.vue
- 修复折线图不同数据库驱动时区问题
- 折线图连线及点显示效果修复
> fix: 折线图时区及展示问题

- internal/container/container.go
- internal/handler/handler.go
- internal/handler/key_handler.go
- internal/router/router.go
- internal/services/key_import_service.go
- internal/services/key_manual_validation_service.go
- internal/services/key_service.go
- internal/services/task_service.go
- web/src/api/keys.ts
- web/src/components/GlobalTaskProgressBar.vue
- web/src/components/keys/KeyCreateDialog.vue
- web/src/types/models.ts
Closes #
- 分组添加密钥功能改为异步任务，并且取消数量限制
> feat: 密钥调整为异步任务，取消数量限制

- .github/workflows/build-go.yml
> 添加自动构建二进制文件功能。

- internal/channel/anthropic_channel.go
- internal/channel/channel.go
- internal/channel/gemini_channel.go
- internal/channel/openai_channel.go
- internal/middleware/middleware.go
- internal/proxy/server.go
- internal/router/router.go
- web/src/api/keys.ts
- web/src/api/logs.ts
> feat: Auth compatible

- internal/channel/anthropic_channel.go
- internal/channel/base_channel.go
- internal/channel/factory.go
- internal/channel/gemini_channel.go
- internal/channel/openai_channel.go
- internal/handler/group_handler.go
- internal/models/types.go
- web/src/components/keys/GroupFormModal.vue
- web/src/components/keys/GroupInfoCard.vue
- web/src/types/models.ts
> feat: 自定义测试路径

- web/src/components/BaseInfoCard.vue
> typo: 秘钥 -> 密钥

- internal/middleware/middleware.go
- internal/router/router.go
> feat: 静态缓存

- web/src/components/keys/GroupList.vue
> fix: 修复新建分组刷新数据异常

- internal/models/types.go
> fix: Key len

- README.md
- README_EN.md
- internal/app/app.go
- internal/config/system_settings.go
- internal/handler/group_handler.go
- internal/handler/settings_handler.go
- internal/middleware/middleware.go
- internal/models/types.go
- internal/router/router.go
- internal/services/group_manager.go
- internal/types/types.go
- internal/utils/config_utils.go
- internal/utils/string_utils.go
- web/src/components/keys/GroupFormModal.vue
- web/src/types/models.ts
- web/src/views/Settings.vue
- 分离认证Key和代理Key，认证Key负责管理端，代理Key负责请求分组代理。
- 代理Key支持系统的全局Key，和分组的专用Key配置。
> feat: 认证Key分离-新增代理Key配置

- internal/channel/gemini_channel.go
> feat: 支持Gemini官方的OpenAi兼容

- web/src/components/common/ProxyKeysInput.vue
- web/src/components/keys/GroupFormModal.vue
- web/src/components/keys/GroupInfoCard.vue
- web/src/utils/display.ts
- web/src/views/Settings.vue
> feat: 代理密钥优化-自动生成随机密钥和复制

- internal/handler/dashboard_handler.go
- internal/models/types.go
- web/src/components/BaseInfoCard.vue
- web/src/types/models.ts
> feat: 统计10分钟RPM

- internal/handler/key_handler.go
- internal/services/key_manual_validation_service.go
- web/src/api/keys.ts
- web/src/components/GlobalTaskProgressBar.vue
- web/src/components/keys/KeyTable.vue
> feat: 分组密钥检查增加状态选项

- internal/channel/anthropic_channel.go
- internal/channel/gemini_channel.go
- internal/channel/openai_channel.go
> fix: 放宽验证Key的错误状态码为2XX

- .github/workflows/release-linux.yml
- .github/workflows/release-macos.yml
- .github/workflows/release-windows.yml
> chore: release macos amd64

- web/src/components/keys/GroupFormModal.vue
> style: 前端优化

- docker-compose.yml
> chore: 考虑安全性，不再映射端口

- internal/handler/key_handler.go
- internal/keypool/provider.go
- internal/router/router.go
- internal/services/key_service.go
- web/src/api/keys.ts
- web/src/components/keys/GroupInfoCard.vue
- web/src/components/keys/KeyTable.vue
> feat: 删除所有密钥

- internal/handler/group_handler.go
- internal/router/router.go
- web/src/api/keys.ts
- web/src/components/keys/GroupCopyModal.vue
- web/src/components/keys/GroupInfoCard.vue
- web/src/types/models.ts
- web/src/views/Keys.vue
> feat: 复制分组

- internal/handler/handler.go
- internal/middleware/middleware.go
> fix: 提升认证逻辑安全性

- internal/channel/anthropic_channel.go
- internal/channel/channel.go
- internal/channel/gemini_channel.go
- internal/channel/openai_channel.go
- internal/handler/group_handler.go
- internal/keypool/validator.go
- internal/models/types.go
- internal/proxy/server.go
- internal/services/group_manager.go
- internal/utils/header_utils.go
- web/src/components/keys/GroupFormModal.vue
- web/src/components/keys/GroupInfoCard.vue
- web/src/components/keys/KeyTable.vue
- web/src/types/models.ts
> feat: 允许自定义Header并支持变量

- internal/container/container.go
- internal/handler/handler.go
- internal/handler/key_handler.go
- internal/keypool/provider.go
- internal/router/router.go
- internal/services/key_delete_service.go
- internal/services/key_import_service.go
- internal/services/task_service.go
- web/src/api/keys.ts
- web/src/components/GlobalTaskProgressBar.vue
- web/src/components/keys/GroupInfoCard.vue
- web/src/components/keys/KeyDeleteDialog.vue
- web/src/components/keys/KeyTable.vue
- web/src/types/models.ts
Closes #206 
- 异步批量删除密钥
- 清除密钥sql优化
> feat: 优化密钥批量操作

- internal/handler/key_handler.go
- internal/services/log_service.go
- web/src/api/keys.ts
- web/src/components/keys/KeyTable.vue
> fix: Conflict between key search and authentication
